on: push

jobs:

  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - id: set-matrix
        run: |
          #matrix=$(./command-to-find-testcases.sh)
          matrix='{"subcommand": ["df", "gs", "cp"], "include": [{"subcommand": "md5", "optionalArgs": "@s"}]}'
          echo $matrix
          echo $matrix | jq .
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  mayhem-async:
    runs-on: ubuntu-latest
    name: 'fuzz'
    needs: matrix
    
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
#       matrix: 
#         subcommand: ["df", "gs", "cp"]
#         # The include keyword that adds a new variable
#         include:
#           - subcommand: md5
#             optionalArgs: "@s"

    steps:
      - id: run-mayhem-async
        name: Simulating an async Mayhem run, resulting in a runId
        run: |
          echo "runId-of-${{ matrix.subcommand }} ${{ matrix.optionalArgs }}" >> runId
          echo "runId=runId-of-${{ matrix.subcommand }} ${{ matrix.optionalArgs }}" >> $GITHUB_OUTPUT

      - name: Invoke workflow with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Check Mayhem
          inputs: '{ "runId": "${{ steps.run-mayhem-async.outputs.runId }}" }'

